# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_result1', models.CharField(max_length=100)),
                ('question_result2', models.CharField(max_length=100)),
                ('question_result3', models.CharField(max_length=100)),
                ('question_result4', models.CharField(max_length=100)),
                ('question_result5', models.CharField(max_length=100)),
                ('question_result6', models.CharField(max_length=100)),
                ('question_result7', models.CharField(max_length=100)),
                ('question_result8', models.CharField(max_length=100)),
                ('question_result9', models.CharField(max_length=100)),
                ('question_result10', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text1', models.CharField(max_length=100)),
                ('question_text2', models.CharField(max_length=100)),
                ('question_text3', models.CharField(max_length=100)),
                ('question_text4', models.CharField(max_length=100)),
                ('question_text5', models.CharField(max_length=100)),
                ('question_text6', models.CharField(max_length=100)),
                ('question_text7', models.CharField(max_length=100)),
                ('question_text8', models.CharField(max_length=100)),
                ('question_text9', models.CharField(max_length=100)),
                ('question_text10', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prospects',
            fields=[
                ('prospect_session', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='formresults',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Forms'),
        ),
        migrations.AddField(
            model_name='formresults',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Prospects'),
        ),
    ]
