# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='submited',
            field=models.CharField(choices=[('T', 'Done'), ('F', 'Dont')], default='F', max_length=1),
        ),
    ]
